### ISSUE TITLE
Null exception on Keycloak:25.0.5

### ISSUE THREAD

**Issue by OrgesKreka** [5-stones/keycloak-email-otp#10]
I am trying to run this library in keycloack 25.0.5, but is throwing the error below everytime i try to sent an otp email.

`2024-11-05 15:41:47 2024-11-05 14:41:47,613 WARN  [org.keycloak.services] (executor-thread-30) KC-SERVICES0013: Failed authentication: java.lang.NullPointerException: Cannot invoke "org.keycloak.models.AuthenticatorConfigModel.getConfig()" because "config" is null
2024-11-05 15:41:47     at com.weare5stones.keycloak.authenticators.emailotp.EmailOTPAuthenticator.authenticate(EmailOTPAuthenticator.java:41)
2024-11-05 15:41:47     at org.keycloak.authentication.DefaultAuthenticationFlow.processSingleFlowExecutionModel(DefaultAuthenticationFlow.java:442)
2024-11-05 15:41:47     at org.keycloak.authentication.DefaultAuthenticationFlow.processAction(DefaultAuthenticationFlow.java:118)
2024-11-05 15:41:47     at org.keycloak.authentication.AuthenticationProcessor.authenticationAction(AuthenticationProcessor.java:1031)
2024-11-05 15:41:47     at org.keycloak.services.resources.LoginActionsService.processFlow(LoginActionsService.java:376)
2024-11-05 15:41:47     at org.keycloak.services.resources.LoginActionsService.processAuthentication(LoginActionsService.java:347)
2024-11-05 15:41:47     at org.keycloak.services.resources.LoginActionsService.authenticate(LoginActionsService.java:339)
2024-11-05 15:41:47     at org.keycloak.services.resources.LoginActionsService.authenticateForm(LoginActionsService.java:405)
2024-11-05 15:41:47     at org.keycloak.services.resources.LoginActionsService$quarkusrestinvoker$authenticateForm_13d428b70e62601585246c086a52f40868a3208e.invoke(Unknown Source)
2024-11-05 15:41:47     at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
2024-11-05 15:41:47     at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
2024-11-05 15:41:47     at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
2024-11-05 15:41:47     at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
2024-11-05 15:41:47     at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
2024-11-05 15:41:47     at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
2024-11-05 15:41:47     at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
2024-11-05 15:41:47     at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
2024-11-05 15:41:47     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2024-11-05 15:41:47     at java.base/java.lang.Thread.run(Thread.java:1583)
2024-11-05 15:41:47 `

Please can you provide me any help on how to solve this issue?

Thanks

**Comment by jspizziri** [comment]
Please read through this issue: https://github.com/5-stones/keycloak-email-otp/issues/8

I've created a [feature ticket to track the status of support](https://github.com/5-stones/keycloak-email-otp/issues/11). PR's welcome.
